language: node_js
node_js:
  - "node" # Latest node version
  - "lts/*" # Latest LTS version
  - "12"
  - "10"
  - "8"

before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@6.13.4; fi

script:
   - grunt standards
   - npm test
   - commitlint-travis

# For code coverage:
after_success:
   cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
